version: "3.9"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  node-app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=mongodb://mongo-container:27017/mydb
    depends_on:
      - mongodb
    


